service: sls-challenge

# App and Org for use with dashboard.serverless.com console.
app: slschallengeapp
org: slschallengeorg

frameworkVersion: "1"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  products-get:
    handler: src/products/get.handler
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
          # authorizer: aws_iam

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
